definitions:
  bet.Bet:
    properties:
      id:
        type: string
      matches:
        items:
          $ref: '#/definitions/match.Match'
        type: array
      score:
        type: integer
    type: object
  config.HealthDetailedRequest:
    properties:
      input:
        minLength: 3
        type: string
    required:
    - input
    type: object
  config.HealthDetailedResponse:
    properties:
      status:
        type: string
      time:
        type: string
    type: object
  match.Match:
    properties:
      date:
        type: string
      matchType:
        $ref: '#/definitions/match.MatchType'
      result:
        $ref: '#/definitions/match.MatchResult'
      round:
        type: integer
      stadium:
        type: string
      teamA:
        type: string
      teamB:
        type: string
    type: object
  match.MatchResult:
    properties:
      teamAScore:
        type: integer
      teamBScore:
        type: integer
    type: object
  match.MatchType:
    enum:
    - 0
    - 1
    type: integer
    x-enum-varnames:
    - MatchTypeGroup
    - MatchTypeKnockout
info:
  contact: {}
  title: Bolao 2026
  version: "1.0"
paths:
  /bets/{id}:
    get:
      parameters:
      - description: Bet ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bet.Bet'
      tags:
      - Bet
  /health:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: Healthy! 2024-01-01 12:00:00
          schema:
            type: string
      tags:
      - Config
  /health-detailed:
    post:
      consumes:
      - application/json
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/config.HealthDetailedRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/config.HealthDetailedResponse'
      tags:
      - Config
  /matches:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/match.Match'
            type: array
      tags:
      - Match
swagger: "2.0"
